### ISSUE TITLE
Where is himax-flash-tool?

### ISSUE THREAD

**Issue by baqwas** [edgeimpulse/firmware-himax-we-i-plus#30]
In trying to follow the tutorial for Himax WE-I Plus, as described in the Edge Impulse tutorial for the board at [https://docs.edgeimpulse.com/docs/development-boards/himax-we-i-plus ](https://docs.edgeimpulse.com/docs/development-boards/himax-we-i-plus) I am missing the **himax-flash-tool** which was not bundled in the himax-we-i.zip archive at the Edge Impulse download site.

How do I get access to the flash utility which is required to the Linux installation script to update the firmware? Thanks.

Kind regards.

P.S.
Searched the [Himax web site](http://himax.com.tw/en/) and Sparkfun site in vain.

**Comment by mmajchrzycki** [comment]
Hi @baqwas 
The `himax-flash-tool` is a part of the [Edge Impulse CLI](https://github.com/edgeimpulse/edge-impulse-cli).
Find out how to instal it here: https://docs.edgeimpulse.com/docs/edge-impulse-cli/cli-installation

**Comment by baqwas** [comment]
Thanks for the update. The issue was that I had a superseded version of Python (under Ubuntu 22.04) that inhibited the installation. Apologies for the poor wording of the issue.

Kind regards.
