### ISSUE TITLE
Building Himax WE-I firmware from Docker errors

### ISSUE THREAD

**Issue by Collin-Hoffman** [edgeimpulse/firmware-himax-we-i-plus#32]
Question/Issue:
When trying to build the Himax WE-I firmware using Docker, I get this error message. I tried looking for the missing folder/file both on my local machine and the GitHub (linked below), but can not find it. Any ideas on what the issue might be / how to get this folder/file?

![image](https://github.com/edgeimpulse/firmware-himax-we-i-plus/assets/67340583/68c08548-5b04-4539-836a-02e2d33c27ba)

Context/Use case:
We are trying to use the Himax WE-I to test custom image processing techniques. Because we are more focused on the signal processing side of things, we don’t have a use for the learning block of an Edge Impulse impulse.

So instead of going through Edge Impulse to create a learning block, flash it to board, etc., we are trying to edit the firmware (from [GitHub - edgeimpulse/firmware-himax-we-i-plus: Ingestion & inferencing firmware for the HiMax WE 1 target](https://github.com/edgeimpulse/firmware-himax-we-i-plus)). To build the firmware, we are using Docker to try to minimize issues with Cmake, dependencies, linkage, etc.

**Comment by mmajchrzycki** [comment]
Thank you for reporting. The issue has been resolved via https://github.com/edgeimpulse/firmware-himax-we-i-plus/commit/a557a80fcfcfb90882c0d521c4808d0cd5f236e8
